#stage 1
FROM node:latest AS builder
WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci

COPY . .

# CORREZIONE RIGA 12: Usa 'build', che è lo standard di Vite
RUN npm run build

#stage 2 
FROM nginx:alpine

COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]
