FROM mongo:7.0

LABEL maintainer="team F1-StratOs"
LABEL version="1.0"
LABEL description="Istanza MongoDB ottimizzata per microservizi"


COPY ./script/config-mongo.js /docker-entrypoint-initdb.d/

# Esposizione porta
EXPOSE 27017

# Volume per persistenza dati
VOLUME ["/data/db"]